config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # twitter認証に必要
  root 'meigens#index'
  resources :meigens, only: [:index, :new ,:show]
  resources :twitters, only: [:update]
  get '/twitter/tweet', to: 'twitter#tweet'
  get'books/new', to: 'books#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meigen.rb
class Meigen < ApplicationRecord
require 'RMagick'
  attr_accessor :image
  belongs_to :user
  mount_uploader :image, ImageUploader

  def create_image(sentence,user)
    font = 'app/assets/fonts/Harenosora.otf'
 	  img = Magick::ImageList.new("app/assets/images/sample/sample.jpg")
    img_resize = img.resize_to_fit(600, 314)
    dr = Magick::Draw.new
    dr.annotate(img_resize, 0, 0, 0, 0, sentence) do
      self.fill = 'black'
      self.font = font
      self.pointsize = 20
      self.gravity = Magick::CenterGravity
    end
    img_resize.write("public/images/#{user.id}-#{Time.now.to_s.delete!(' +:-')}.jpg")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[twitter]

  has_many :meigens

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email || User.dummy_email(auth)
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.nickname = auth.info.nickname
       # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!

    end
  end

  private
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!  #コントローラーに設定して、ログイン済ユーザーのみにアクセスを許可する
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require "./app/modules/book"

  def new
    url = "https://www.googleapis.com/books/v1/volumes"
    query = {title: params["title"], author:params["author"]}
    @book = BooksAPI.fetch(url, query)
    render :json => @book
  end

end

app/controllers/meigens_controller.rb
class MeigensController < ApplicationController
  before_action :authenticate_user!, only: %i[index new]

  def index
  end

  def new
    @meigen = Meigen.new
  	@user = current_user
    @meigen.create_image(params[:sentence],@user)
    @meigen.content = "#{@user.id}-#{Time.now.to_s.delete!(' +:-')}.jpg"
    @meigen.user = @user
    @meigen.book_url = "www.sakurainaoya"
    @meigen.save
    @twitter_card = "#{root_url}meigens/#{@meigen.id}"
  end

  def show
  	@meigen = Meigen.find(params[:id])
  	@user = @meigen.user
  	@twitter_card = "#{root_url}meigens/#{@meigen.id}"
  	render :layout => 'twitter_card'
  end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  before_action :set_twitter_client

  def tweet
    @twitter.update params[:text]
    redirect_to root_path
  end

  private

  def set_twitter_client
    @twitter = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_API_KEY"]
      config.consumer_secret     = ENV["TWITTER_API_SECRET"]
      config.access_token        = session[:oauth_token]
      config.access_token_secret = session[:oauth_token_secret]
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    auth = request.env['omniauth.auth']
    @user = User.from_omniauth(auth)
    @user.name = auth['info']['name']
    @user.nickname = auth['info']['nickname']
    @user.save

    # 投稿に必要なauth_token, secret_tokenも取得する
    session[:oauth_token] = auth['credentials']['token']
    session[:oauth_token_secret] = auth['credentials']['secret']

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      # session["devise.twitter_data"] = request.env["omniauth.auth"]
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      #extra内の情報が大きすぎるため、除外する。
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meigens_helper.rb
module MeigensHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title MeigenApp
    = csrf_meta_tags
    = csp_meta_tag
    %link{rel: "stylesheet", crossorigin: "anonymous", integrity: "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body
    / = render "partial/header"
    = yield
    %script{crossorigin: "anonymous", integrity: "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", src: "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", src: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{type: 'text/javascirpt'}
      $('[data-toggle="popover"]').popover()

app/views/layouts/twitter_card.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "summary_large_image", :name => "twitter:card"}
    %meta{:content => "@#{@user.nickname}", :name => "twitter:site"}
    %meta{:content => "#{@twitter_card}", :property => "og:url"}
    %meta{:content => "名言APP", :property => "og:title"}
    %meta{:content => "あなたが共感した名言は？", :property => "og:description"}
    %meta{:content => "http://meigenapp.herokuapp.com/images/#{@meigen.content}", :property => "og:image"}
    %title MeigenApp
    = csrf_meta_tags
    = csp_meta_tag
    %link{rel: "stylesheet", crossorigin: "anonymous", integrity: "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    / = render "partial/header"
    = yield
    %script{crossorigin: "anonymous", integrity: "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", src: "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", src: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"}

app/views/meigens/index.html.haml
.container-fluid
  .row
    .col-md-6.offset-md-3.col-sm-10.offset-sm-1.col-12.mt-5
      .text-center
        %h1 名言アプリ
        .small あなたの共感した名言呟きませんか？
      .border.p-md-4.p-2.border-dark
        .form-group.mt-2
          = label_tag :text, "シェアしたい名言"
          = text_area_tag :text, nil, class: 'form-control', rows: "3" ,form: "create-image", name: "sentence"
        %form.pt-2
          %p.mb-2 本を検索する
          .border.p-md-3.p-2
            .form-group
              %label{for: "exampleFormControlInput1"}本のタイトル
              %input#title.form-control{placeholder: "", type: "*"}
            .form-group
              %label{for: "exampleFormControlInput1"}著者
              %input#author.form-control{placeholder: "", type: "*"}
          %button.btn.btn-primary.mt-4{type: "button", onClick: 'loadText()'} 本を検索
        #src_rslt_container.pt-3
        #input_book_container.pt-2
      = form_tag "/meigens/new", method: "GET", id: "create-image", class: "mt-3" do
        .text-center
          = submit_tag '画像生成', class: 'btn btn-primary'
      - if user_signed_in?
        .text-center.mb-5
          = link_to "ログアウト" ,destroy_user_session_path,method: :delete

app/views/meigens/new.html.haml
.container-fluid
  .row
    .col-md-3.col-sm-2.col-12
    .col-md-6.co1-sm-8.col-12.text-center
      %h3.mt-5 名言画像を生成しました
      - if "public/images/#{@meigen.content}"
        = image_tag "/images/#{@meigen.content}" ,class: "img-fluid"
      = form_tag twitter_tweet_path, method: "GET" do
        .form-group.mt-4
          = label_tag :text, "シェアしたい名言"
          = text_area_tag :text, @twitter_card, class: 'form-control', rows: "5" , name: "text"
        .small.samll.mb-2 ＊ツイートするとあなたのタイムラインに直接投稿されます。
        = submit_tag 'ツイートする', class: 'btn btn-primary'
      .mt-4
        = link_to "戻る" ,root_path

app/views/meigens/show.html.haml
.container-fluid
  .row
    .col-md-3.col-sm-2.col-12
    .col-md-6.co1-sm-8.col-12.text-center
      %h2.mt-5 名言画像
      = image_tag "/images/#{@meigen.content}" ,class: "img-fluid"
      %p.mt-5 こちらの本について
      = link_to "名言画像を作る" ,root_path

app/views/partial/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.main-bk-color
  %a.navbar-brand{:href => root_path} Meigen
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "#"}
          Home
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => "#"} Link
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Dropdown
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "#"} Action
          %a.dropdown-item{:href => "#"} Another action
          .dropdown-divider
          %a.dropdown-item{:href => "#"} Something else here
      %li.nav-item
        %a.nav-link.disabled{:href => "#"} Disabled
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search